# Page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Hear Ye                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Know your representatives

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Hear Ye LLC                                
your_link                                 : https://velnota.com/users/Hear-Ye/                     
your_city                                 : Detroit                                
email_address                             : support@hearye.us
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : HearYeOfficial
github_username                           : Hear-Ye
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Your Daily Political News
    description                           : Designed for bipartisan perspectives on political issues, cited with articles from trustworthy organizations regardless of party
    fontawesome_icon_name                 : box-ballot

  - title                                 : Short + Long = Trustworthy
    description                           : We write "short" articles for those in a hurry with dropdowns that show further, longer analysis on issues
    fontawesome_icon_name                 : link

  - title                                 : Vote Analytics
    description                           : Vote in each issue to compare your vote to your neighbors
    fontawesome_icon_name                 : mobile

  - title                                 : Your Representatives
    description                           : See how your representatives vote over time and per Congressional bill
    fontawesome_icon_name                 : play-circle

  - title                                 : Contributions Graph
    description                           : See how you've been voting over time with our contributions graph
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Coming soon!
    description                           : The same Velnota comment sections you know and love with a ranking system based on smart conversations and balance between party lines
    fontawesome_icon_name                 : sync

  - title                                 : Coming soon!
    description                           : Notifications for when the next bill or news fragment arrives
    fontawesome_icon_name                 : adjust
  
  - title                                 : Coming soon!
    description                           : View all Congressional bills to be considered -- every single day
    fontawesome_icon_name                 : star

  - title                                 : Coming soon!
    description                           : Accessibility is fully supported -- including everyone in the conversation
    fontawesome_icon_name                 : info-circle



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
